sudo: required
language: scala

before_install:
- git clone git://github.com/jedisct1/libsodium.git
- cd libsodium
- git checkout 1.0.15
- ./autogen.sh
- ./configure && make check
- sudo make install
- sudo ldconfig
- cd ..
- sudo -E apt-get -yq --no-install-suggests --no-install-recommends install swig

scala:
  - 2.12.4
  - 2.11.11

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/libsodium

jdk:
  - oraclejdk8
  - openjdk8

script:
  - bash sodium_setup.sh
  - sbt ++$TRAVIS_SCALA_VERSION clean
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION tut

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "jmcardon/tsec" && test $TRAVIS_JDK_VERSION == "oraclejdk8" && sbt ++$TRAVIS_SCALA_VERSION publish
